#+TITLE:    leptus_router module
#+AUTHOR:   Sina Samavati
#+EMAIL:    sina.samv@gmail.com
#+OPTIONS:  ^:nil num:nil

* leptus_router module
  :PROPERTIES:
  :CUSTOM_ID: leptus_router
  :END:

  This module is used for gathering routes and categorizing the dispatch the way
  the order of routes matters in Cowboy.

** Types
   :PROPERTIES:
   :CUSTOM_ID: types
   :END:

   #+BEGIN_SRC erlang
   Handlers = [{HostMatch, [{module(), State :: any()}]}]
   Routes   = cobwboy_router:routes()
   Dispatch = cowboy_router:dispatch_rules()
   #+END_SRC

** Functions
  :PROPERTIES:
  :CUSTOM_ID: functions
  :END:

*** paths/1
    :PROPERTIES:
    :CUSTOM_ID: paths-1
    :END:

    Gathers and makes a list of Cowboy routes.

    #+BEGIN_SRC erlang
    paths(Handlers) -> Routes
    #+END_SRC

*** sort_dispatch/1
    :PROPERTIES:
    :CUSTOM_ID: sort_dispatch-1
    :END:

    Sorts dispatch the way order of routes matters in Cowboy.

    #+BEGIN_SRC erlang
    sort_dispatch(Dispatch) -> Dispatch
    #+END_SRC

*** static_file_routes/1
    :PROPERTIES:
    :CUSTOM_ID: static_file_routes-1
    :END:

    Makes routes to serve static files using Cowboy static handler.

    #+BEGIN_SRC erlang
    static_file_routes({HostMatch, Dir | {priv_dir, App, Dir}}) -> Routes
    #+END_SRC

    NOTE: ~{priv_dir, App, Dir}~ will use the directory ~App/priv/Dir~.

    Assume we want to serve static files in ~/var/www~ which contains
    ~index.html~ and ~static/css/style.css~, we call this function like the
    following:

    #+BEGIN_SRC erlang
    static_file_routes({'_', "/var/www"})
    #+END_SRC

    and this will return:

    #+BEGIN_SRC erlang
    [{'_', [
            {"/", cowboy_static, {file, "/var/www/index.html"}},
            {"/index.html", cowboy_static, {file, "/var/www/index.html"}},
            {"/static/css/style.css", cowboy_static, {file, "/var/www/static/css/style.css"}}
           ]}]
    #+END_SRC
