#+AUTHOR:   Sina Samavati
#+EMAIL:    sina.samv@gmail.com
#+TITLE:    leptus_router

* Module
  :PROPERTIES:
  :CUSTOM_ID: module
  :END:

  leptus_router

  This module is used for collecting routes, and sorting them.

* Types
  :PROPERTIES:
  :CUSTOM_ID: types
  :END:

  #+BEGIN_SRC
  Handlers = [{HostMatch, [{module(), State :: any()}]}]
  Routes   = cobwboy_router:routes()
  Dispatch = cowboy_router:dispatch_rules()
  #+END_SRC

** Functions
  :PROPERTIES:
  :CUSTOM_ID: functions
  :END:

** paths/1
   :PROPERTIES:
   :CUSTOM_ID: paths-1
   :END:

   Gathers and makes a list of Cowboy routes.

   #+BEGIN_SRC
   paths(Handlers) -> Routes
   #+END_SRC

** sort_dispatch/1
   :PROPERTIES:
   :CUSTOM_ID: sort_dispatch-1
   :END:

   Sorts dispatch the way order of routes matters in Cowboy.

   #+BEGIN_SRC
   sort_dispatch(Dispatch) -> Dispatch
   #+END_SRC

** static_file_routes/1
   :PROPERTIES:
   :CUSTOM_ID: static_file_routes-1
   :END:

   Makes routes to serve static files using Cowboy static handler.

   #+BEGIN_SRC
   static_file_routes({HostMatch, Dir | {priv_dir, App, Dir}}) -> Routes
   #+END_SRC

   NOTE: ~{priv_dir, App, Dir}~ will use the directory ~App/priv/Dir~.

   Assume we want to serve static files in ~/var/www~ which contains
   ~index.html~ and ~static/css/style.css~, we call this function like the
   following:

   #+BEGIN_SRC
   static_file_routes({'_', "/var/www"})
   #+END_SRC

   And that will return:

   #+BEGIN_SRC
   [{'_', [
           {"/", cowboy_static, {file, "/var/www/index.html"}},
           {"/index.html", cowboy_static, {file, "/var/www/index.html"}},
           {"/static/css/style.css", cowboy_static, {file, "/var/www/static/css/style.css"}}
          ]}]
   #+END_SRC
